GET https://my-blogyy.herokuapp.com/blogs/6229c6d8ff5bfb1ffe7c5686

###
GET https://my-blogyy.herokuapp.com/blogs

###
POST https://my-blogyy.herokuapp.com/blogs
Content-type: application/json

{
    "title":"Paris",
    "content":"Paris is one of the most beautiful cities in the world. It is known worldwide for the Louvre Museum, Notre-Dame cathedral, and the Eiffel tower. It has a reputation of being a romantic and cultural city. The city is also known for its high-quality gastronomy and the terraces of its cafés",
    "img":"https://www.istorytime.com/wp-content/uploads/2017/12/eiffel-tower-1280022_1280.jpg"
}

###
DELETE  https://my-blogyy.herokuapp.com/blogs

###
PATCH https://my-blogyy.herokuapp.com/blogs

{
    "img":"https://www.istorytime.com/wp-content/uploads/2017/12/eiffel-tower-1280022_1280.jpg"
}