GET https://my-blogyy.herokuapp.com/users/621f27c1b5fd27ccd4c791ca

###
GET https://my-blogyy.herokuapp.com/users

###
POST https://my-blogyy.herokuapp.com/users/signup
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMmFmMTU5M2NkMmRlYTMwMmU1OTFiYiIsImlhdCI6MTY0NzY4MDM3NSwiZXhwIjoxNjQ3NzY2Nzc1fQ.x48l-te8fyJIg8G__DI-iq8Z8vmvd5quSMduomroJdc

{
     "name":"Samsung" ,
      "email":"samsung@gmail.com" ,
      "password":"123456" ,
      "phone_number": "0625589996",
}

###
DELETE  http://localhost:9339/users/621f2863b5fd27ccd4c791d1

