GET http://localhost:9339/users/621f27c1b5fd27ccd4c791ca

###
GET http://localhost:9339/users

###
POST http://localhost:9339/users
Content-type: application/json

{
    "name":"",
    "email":"",
    "password":"",
    "phone_number":""
    
}

###
DELETE  http://localhost:9339/users/621f2863b5fd27ccd4c791d1

